our_yachts1save
Niko-1515/Team-project-YachtJet- pull request #18
Opened 2024-08-09 21:38 UTC by KyryloPiven

2024-08-09 23:18 UTC, Niko-1515 requested changes
- на планшетній версії змінити шрифт елементу h1 згідно макету
- h1 може бути один на сторінці  і він в херо
-  в самих картках (our-item) на планшетній версії також шрифт інший
- на десктопній роз'їхалась внутрішня геометрія карток (our-item)

2024-08-10 12:03 UTC, Niko-1515 requested changes
Все класно)) тільни верхній маржин треба збільнити неа десктопних версіях

2024-08-10 20:56 UTC, KyryloPiven commented
correct buttom

2024-08-10 21:28 UTC, Niko-1515 approved these changes

2024-08-10 21:29 UTC, merged